# Generated by Django 3.1.7 on 2021-05-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210429_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listingid',
        ),
    ]
