# Generated by Django 3.1.7 on 2021-05-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_watchlist_listingid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='starting_bid',
            new_name='current_bid',
        ),
    ]
