# Generated by Django 3.1.7 on 2021-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
