# Generated by Django 3.1.7 on 2021-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210505_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
