# Generated by Django 3.1.7 on 2021-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210505_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.CharField(max_length=64),
        ),
    ]
