# Generated by Django 3.1.7 on 2021-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210505_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listingid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
