# Generated by Django 3.1.7 on 2021-05-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210511_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingid',
            new_name='productid',
        ),
    ]
