# Generated by Django 3.1.7 on 2021-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210511_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='productid',
            field=models.IntegerField(),
        ),
    ]
